#ifndef HLIDAC_PES_CONFIGURE_RCPSP_H
#define HLIDAC_PES_CONFIGURE_RCPSP_H

/* SCHEDULE SOLVER */
#define SWAP_RANGE 20
#define PRECEDENCE_PENALTY 3

/* TABU LIST */
#define TABU_LIST_SIZE 500

/* CUDA CONFIGURE */
#define NUMBER_OF_BLOCK_PER_MULTIPROCESSOR 2

/* HASH PENALTY */
#define HASH_PENALTY_WEIGHT 10

#endif

