#include <stdint.h>
#include "ConfigureRCPSP.h"

namespace ConfigureRCPSP {
	/* SCHEDULE SOLVER SETTINGS */
	uint32_t TABU_LIST_SIZE = DEFAULT_TABU_LIST_SIZE;
	uint32_t NUMBER_OF_ITERATIONS = DEFAULT_NUMBER_OF_ITERATIONS;
	uint32_t MAXIMAL_NUMBER_OF_ITERATIONS_SINCE_BEST = DEFAULT_MAXIMAL_NUMBER_OF_ITERATIONS_SINCE_BEST;
	uint32_t SWAP_RANGE = DEFAULT_SWAP_RANGE;
	uint32_t DIVERSIFICATION_SWAPS = DEFAULT_DIVERSIFICATION_SWAPS;
	uint32_t NUMBER_OF_SET_SOLUTIONS = DEFAULT_NUMBER_OF_SET_SOLUTIONS;
	uint32_t NUMBER_OF_BLOCKS_PER_MULTIPROCESSOR = DEFAULT_NUMBER_OF_BLOCKS_PER_MULTIPROCESSOR;
	uint32_t MAXIMAL_VALUE_OF_READ_COUNTER = DEFAULT_MAXIMAL_VALUE_OF_READ_COUNTER;
	bool WRITE_RESULT_FILE = (DEFAULT_WRITE_RESULT_FILE == 1 ? true : false);	
}

