#ifndef HLIDAC_PES_CONFIGURE_RCPSP_H
#define HLIDAC_PES_CONFIGURE_RCPSP_H

/* SCHEDULE SOLVER */
#define SWAP_RANGE 60

/* TABU LIST */
#define TABU_LIST_SIZE 800

/* CUDA CONFIGURE */
#define NUMBER_OF_BLOCK_PER_MULTIPROCESSOR 2

/* SOLUTION SET SIZE */
#define SOLUTION_SET_SIZE 8

#endif

