#ifndef HLIDAC_PES_CUDA_CONSTANTS_H
#define HLIDAC_PES_CUDA_CONSTANTS_H

#define NUMBER_OF_ACTIVITIES 122
#define NUMBER_OF_RESOURCES 4
#define MAXIMUM_CAPACITY_OF_RESOURCE 91
#define TOTAL_SUM_OF_CAPACITY 331

#endif
